export const LANGUAGES = {
  amharic: {
    code: 'amharic',
    name: 'አማርኛ (Amharic)',
    shortName: 'አማርኛ',
    flag: '🇪🇹',
    welcome: 'ጤና AI - የሕክምና ትሪያጅ እና ቴሌ-ዶክተር መድረክ',
    subtitle: 'ለገጠር ጤና ኤክስቴንሽን ሰራተኞች እና ህበረተሰብ በድምፅ እና በፎቶ የተደገፈ የኤአይ ትሪያጅ',
    recordVoiceInstruction: 'የሕመም ምልክቱን ለመናገር ቀይ አዝራሩን ይጫኑ',
    recording: 'እየተቀረፀ ነው... በግልፅ ይናገሩ',
    stopRecording: 'ቅዳውን ጨርስ',
    uploadPhotoInstruction: 'የቁስል ወይም የቆዳ ችግር ፎቶ ያንሱ/ያያይዙ',
    patientNamePlaceholder: 'የታካሚው ሙሉ ስም',
    patientAgePlaceholder: 'ዕድሜ',
    submitTriage: 'የኤአይ ትሪያጅ ምርመራ ጀምር',
    analyzing: 'ጉግል ጌሚኒ ኤአይ ምልክቶቹን እየመረመረ ነው...',
    triageUrgency: 'የሕመም አስቸኳይነት ደረጃ',
    redCritical: '🚨 ከፍተኛ አደጋ (ወዲያውኑ ወደ ሆስፒታል/ቴሌ-ዶክተር)',
    yellowUrgent: '⚠️ መካከለኛ አደጋ (በ 24-48 ሰዓት ውስጥ መታየት ያለበት)',
    greenRoutine: '✅ ዝቅተኛ አደጋ (የቤት ውስጥ እንክብካቤ)',
    listenNativeAdvice: 'የኤአይ የሕክምና ምክር በድምፅ ያዳምጡ 🔊',
    connectDoctor: 'ከቴሌ-ዶክተር ጋር በቪዲዮ ጥሪ ይገናኙ 📹',
    hewPortal: 'የጤና ኤክስቴንሽን ፖርታል',
    doctorPortal: 'የሐኪሞች ፖርታል (Adama / Addis Ababa)',
    analyticsPortal: 'የክልል ጤና ትንታኔ (Referral Flow)'
  },
  oromo: {
    code: 'oromo',
    name: 'Afaan Oromoo',
    shortName: 'Oromoo',
    flag: '🇪🇹',
    welcome: 'Tena AI - Sirna Triage Fayyaa fi Tele-Doctor Multi-lingual',
    subtitle: 'Hojjattoota Eksteenshinii Fayyaa Baadiyyaatiif Qorannoo Fayyaa Sagaleedhaan fi Suuraadhaan',
    recordVoiceInstruction: 'Mallattoolee dhukkubaa dubbachuuf qabduu diimaa tuqaa',
    recording: 'Waraabamaa jira... Ifatti dubbadhaa',
    stopRecording: 'Waraabbii Dhaabi',
    uploadPhotoInstruction: 'Suuraa madaa ykn rakkoo gogaa kaasaa',
    patientNamePlaceholder: 'Maqaa Guutuu Dhukkubsataa',
    patientAgePlaceholder: 'Umrii',
    submitTriage: 'Qorannoo Gemini AI Jalqabi',
    analyzing: 'Google Gemini AI mallattoolee qorachaa jira...',
    triageUrgency: 'Sadarkaa Ariifachiisummaa Dhukkubaa',
    redCritical: '🚨 Balaa Olaanaa (Battalatti gara Hospitaalaa/Tele-Doctor)',
    yellowUrgent: '⚠️ Balaa Giddu-galeessaa (Sa'aatii 24-48 keessatti)',
    greenRoutine: '✅ Balaa Salphaa (Gorsa Mana Keessaa)',
    listenNativeAdvice: 'Gorsa Fayyaa AI Sagaleedhaan Dhaggeeffadhaa 🔊',
    connectDoctor: 'Ogeessa Fayyaa Wajjin Viidiyoodhini Wal-qunnamaa 📹',
    hewPortal: 'Portaalii Eksteenshinii Fayyaa',
    doctorPortal: 'Portaalii Ogeeyyii Fayyaa',
    analyticsPortal: 'Xiinxala Fayyaa Naannoo'
  },
  tigrinya: {
    code: 'tigrinya',
    name: 'ትግርኛ (Tigrinya)',
    shortName: 'ትግርኛ',
    flag: '🇪🇹',
    welcome: 'ጤና AI - መድረክ ሕክምና ትሪያጅን ቴሌ-ዶክተርን',
    subtitle: 'ንገጠር ኤክስቴንሽን ሰራሕተኛታት ብድምጺን ብስእሊን ዝተደገፈ AI ትሪያጅ',
    recordVoiceInstruction: 'ምልክታት ሕማም ንምዝራብ ቀይሕ বুልዮ ጠውቁ',
    recording: 'ይቀዳሕ ኣሎ... ብንጹር ተዛረቡ',
    stopRecording: 'ምቕዳሕ ኣቋርፅ',
    uploadPhotoInstruction: 'ስእሊ ቁስሊ ወይ ናይ ቆርበት ሕማም ኣእትዉ',
    patientNamePlaceholder: 'ምሉእ ስም ሕሙም',
    patientAgePlaceholder: 'ዕድመ',
    submitTriage: 'ምርመራ Gemini AI ጀምር',
    analyzing: 'Google Gemini AI ምልክታት የጽንዕ ኣሎ...',
    triageUrgency: 'ደረጃ ህጹጽነት ሕማም',
    redCritical: '🚨 ላዕለዋይ ሓደጋ (ብቕልጡፍ ናብ ሆስፒታል/ቴሌ-ዶክተር)',
    yellowUrgent: '⚠️ ማእከላይ ሓደጋ (ኣብ ውሽጢ 24-48 ሰዓታት)',
    greenRoutine: '✅ ቀሊል ሓደጋ (ናይ ገዛ ክንክን)',
    listenNativeAdvice: 'ምክሪ ሕክምና AI ብድምጺ ስምዑ 🔊',
    connectDoctor: 'ምስ ሓኪም ብቪዲዮ ተራኸቡ 📹',
    hewPortal: 'ፖርታል ኤክስቴንሽን ሓኪም',
    doctorPortal: 'ፖርታል ሓካይም',
    analyticsPortal: 'ትንተና ጥዕና ዞባ'
  },
  english: {
    code: 'english',
    name: 'English',
    shortName: 'ENG',
    flag: '🌐',
    welcome: 'Tena AI - Multilingual Medical Triage & Tele-Doctor Network',
    subtitle: 'Voice & Vision AI Triage for Rural Health Extension Workers in Ethiopia',
    recordVoiceInstruction: 'Tap red microphone button to record patient symptoms',
    recording: 'Recording audio... Speak clearly',
    stopRecording: 'Stop Recording',
    uploadPhotoInstruction: 'Take or upload wound / skin photo',
    patientNamePlaceholder: 'Full Patient Name',
    patientAgePlaceholder: 'Age',
    submitTriage: 'Start Gemini AI Diagnostics',
    analyzing: 'Google Gemini AI analyzing symptoms & images...',
    triageUrgency: 'Triage Urgency Rating',
    redCritical: '🚨 CRITICAL RED (Immediate Tele-Doctor Video Referral)',
    yellowUrgent: '⚠️ URGENT YELLOW (Health Center within 24-48h)',
    greenRoutine: '✅ ROUTINE GREEN (Home Monitoring & Care)',
    listenNativeAdvice: 'Listen to AI Audio Guidance 🔊',
    connectDoctor: 'Start WebRTC Video Doctor Session 📹',
    hewPortal: 'Health Worker Portal',
    doctorPortal: 'Doctor Queue (Addis Ababa / Adama)',
    analyticsPortal: 'Regional Referral Analytics'
  }
};
